stages:
  - build
  - test

build-be-dev:
  stage: build
  image: composer:2
  script:
    - composer install --optimize-autoloader --no-suggest --no-interaction

build-be:
  stage: build
  image: composer:2
  script:
    - composer install --optimize-autoloader --no-suggest --no-interaction --no-dev

build-fe:
  stage: build
  image: node:16
  script:
    - npm install
    - npm run production

test-docker:
  stage: test
  image: docker:latest
  script:
    - docker build -f docker/application/application.Dockerfile .
    - docker build -f docker/tooling/tooling.Dockerfile .
