title: Spenden
template: templates/donations/show
layout: layout
revisions: false
route: 'spenden/{slug}'
sort_dir: asc
date_behavior:
  past: public
  future: private
preview_targets:
  -
    label: Entry
    url: '{permalink}'
